### ISSUE TITLE
Include preview

### ISSUE THREAD

**Issue by ishepard** [homoluctus/slatify#1]
Hi!
Thank you for the beautiful action!

It could be very nice to have the preview of the message. Currently, this is the notification:
![Screenshot 2019-09-02 at 11 35 49](https://user-images.githubusercontent.com/9136821/64105162-f4984b80-cd75-11e9-86fd-c10c3b820bd4.png)
Maybe we can find a way to set the preview or make it customizable? 

thanks!

**Comment by homoluctus** [comment]
Thanks @ishepard 

Your idea is cool !!!
So, I customized to display the preview of the message.

https://github.com/homoluctus/slatify/blob/master/preview.png

**Comment by homoluctus** [comment]
> Hi!
> Thank you for the beautiful action!
> 
> It could be very nice to have the preview of the message. Currently, this is the notification:
> ![Screenshot 2019-09-02 at 11 35 49](https://user-images.githubusercontent.com/9136821/64105162-f4984b80-cd75-11e9-86fd-c10c3b820bd4.png)
> Maybe we can find a way to set the preview or make it customizable?
> 
> thanks!

@ishepard Thanks!

Your idea is cool !!!
So, I customized to display the preview of the message.

<img width="343" alt="preview" src="https://user-images.githubusercontent.com/22735969/64131297-a41aff80-ce02-11e9-9bbe-09351ed952fe.png">

**Comment by ishepard** [comment]
That looks pretty cool! Thanks!
